//! `ledger-entry-hash.json`: the ledger entry hash layout (#1226), generated by an independent
//! Python encoder (`scripts/gen-ledger-entry-vectors.py`).

use avalon_protocol::canonical_payload::{canonicalize, parse_strict};
use avalon_protocol::ledger_entry::{
    entry_hash, entry_signing_bytes, parse_hash, payload_hash, timestamp_micros, EntryHashError,
    EntryHashInput,
};
use serde_json::Value;
use time::format_description::well_known::Rfc3339;
use time::OffsetDateTime;
use uuid::Uuid;

fn load() -> Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../conformance/vectors/ledger-entry-hash.json");
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

/// Builds the entry bytes from a vector input, the way an SDK would.
fn build(input: &Value) -> Result<(Vec<u8>, [u8; 32]), EntryHashError> {
    let text = |k: &str| input[k].as_str().unwrap().to_string();
    let prev = parse_hash("prev_hash", &text("prevHashHex"))?;
    let payload_hash = match input["payloadHashHex"].as_str() {
        Some(h) => parse_hash("payload_hash", h)?,
        None => payload_hash_of(&text("payloadJsonUtf8")),
    };
    let seq: u64 = text("seq")
        .parse()
        .map_err(|_| EntryHashError::OutOfRange("seq"))?;
    let version = u16::try_from(input["version"].as_i64().unwrap())
        .map_err(|_| EntryHashError::OutOfRange("version"))?;
    let micros: i64 = text("timestampUnixMicros").parse().unwrap();
    let message = entry_signing_bytes(&EntryHashInput {
        network_id: &text("networkId"),
        shard_id: &text("shardId"),
        seq,
        prev_hash: &prev,
        event_id: Uuid::parse_str(&text("eventId")).unwrap(),
        kind: &text("kind"),
        issuer: &text("issuer"),
        subject: &text("subject"),
        payload_hash: &payload_hash,
        timestamp_micros: micros,
        version,
    })?;
    let hash = {
        use sha2::{Digest, Sha256};
        Sha256::digest(&message).into()
    };
    Ok((message, hash))
}

fn payload_hash_of(json: &str) -> [u8; 32] {
    payload_hash(&parse_strict(json).unwrap()).unwrap()
}

#[test]
fn ledger_entry_hash_matches_shared_vectors() {
    let doc = load();
    for v in doc["vectors"].as_array().unwrap() {
        let name = v["name"].as_str().unwrap();
        let (input, expected) = (&v["input"], &v["expected"]);
        if let Some(json) = input["payloadJsonUtf8"].as_str() {
            let value = parse_strict(json).unwrap();
            assert_eq!(
                canonicalize(&value).unwrap(),
                expected["payloadCanonicalUtf8"].as_str().unwrap(),
                "[{name}] canonical payload"
            );
            assert_eq!(
                hex::encode(payload_hash(&value).unwrap()),
                expected["payloadHashHex"].as_str().unwrap(),
                "[{name}] payload hash"
            );
        }
        let (message, hash) = build(input).unwrap_or_else(|e| panic!("[{name}] {e}"));
        assert_eq!(
            hex::encode(&message),
            expected["signingBytesHex"].as_str().unwrap(),
            "[{name}] bytes"
        );
        assert_eq!(
            hex::encode(hash),
            expected["entryHashHex"].as_str().unwrap(),
            "[{name}] hash"
        );
        let time =
            OffsetDateTime::parse(input["eventTimestampRfc3339"].as_str().unwrap(), &Rfc3339)
                .unwrap();
        assert_eq!(
            timestamp_micros(time).unwrap().to_string(),
            input["timestampUnixMicros"].as_str().unwrap(),
            "[{name}] timestamp micros"
        );
    }
}

#[test]
fn ledger_entry_hash_rejects_per_shared_vectors() {
    let doc = load();
    for v in doc["rejectVectors"].as_array().unwrap() {
        let name = v["name"].as_str().unwrap();
        let want = v["expected"]["error"].as_str().unwrap();
        let got = match build(&v["input"]) {
            Err(EntryHashError::InvalidHash(_)) => "invalid_hash",
            Err(EntryHashError::OutOfRange(_)) => "out_of_range",
            Err(other) => panic!("[{name}] unexpected {other}"),
            Ok(_) => panic!("[{name}] accepted"),
        };
        assert_eq!(got, want, "[{name}]");
    }
}

#[test]
fn entry_hash_function_agrees_with_the_vector_hashes() {
    let doc = load();
    let v = &doc["vectors"][0];
    let input = &v["input"];
    let prev = parse_hash("p", input["prevHashHex"].as_str().unwrap()).unwrap();
    let ph = payload_hash_of(input["payloadJsonUtf8"].as_str().unwrap());
    let hash = entry_hash(&EntryHashInput {
        network_id: input["networkId"].as_str().unwrap(),
        shard_id: input["shardId"].as_str().unwrap(),
        seq: 1,
        prev_hash: &prev,
        event_id: Uuid::parse_str(input["eventId"].as_str().unwrap()).unwrap(),
        kind: input["kind"].as_str().unwrap(),
        issuer: input["issuer"].as_str().unwrap(),
        subject: input["subject"].as_str().unwrap(),
        payload_hash: &ph,
        timestamp_micros: 1_767_323_045_123_456,
        version: 1,
    })
    .unwrap();
    assert_eq!(hex::encode(hash), v["expected"]["entryHashHex"]);
}
