-- Issue #154: `GET /guilds/discover`'s `tag=` filter does a case-insensitive
-- exact match against `guilds.tag`. `guilds_recruiting_idx` (#153) already
-- covers the `recruiting` filter; the matching index for `tag` already
-- exists too — `guilds_tag_lower_idx`, a unique index on `lower(tag)` from
-- `0008_guilds` (tag uniqueness is case-insensitive), so no new index is
-- needed here. The free-text `q=` search (`ILIKE '%...%'` over name/tag/
-- description) is deliberately NOT given a trigram index here — that's the
-- kind of real read-model/indexing work #42's indexer migration owns, not
-- something to bolt onto the milestone-1 `server`-side stand-in this ticket
-- documents itself as (see `docs/architecture/guilds.md`).
SELECT 1;
